### ISSUE TITLE
Font awsome loader breaks in webpack 2.

### ISSUE THREAD

**Issue by vpanjganj** [shakacode/font-awesome-loader#2]
![screen shot 2016-07-25 at 14 43 52](https://cloud.githubusercontent.com/assets/8151667/17103821/1ca8a754-5278-11e6-8d6e-0cb53916ee4d.png)

It seems it can be simply prevented by changing 
```
require("style!css!sass!./font-awesome-styles!./font-awesome.config.js");
```
to
```
require("style!css!sass!./font-awesome-styles.loader!./font-awesome.config.js");
```
in `font-awesome-loader/index.js`. This change wont break anything in older webpack versions. I checked on bootstrap-loader basic example, but it may impact other things I don't know of.

At the moment I'm blocked by this while working on Extract text plugin 2 support (It needs webpack 2) for bootstrap loader (I'm updating some of the dependencies in example projects).

**Comment by justin808** [comment]
See #3
