### ISSUE TITLE
Rework to work with webpack 2 better

### ISSUE THREAD

**Issue by bebraw** [shakacode/font-awesome-loader#7]
Hi,

We've been reworking [extract-text-webpack-plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin) internals. Now `extract` (the loader) portion returns an object that can contain functions. That doesn't go well with font-awesome-loader and serializing to a string doesn't quite work as it's a lossy transformation.

I had a quick chat with Tobias about the topic and here are the recommendations we came up with:

## Rework the Configuration Approach

Instead of going through an entry, you could try

```
[
  {
    test: /font-awesome\.config\.js/
    use: [
      { loader: "style-loader", options: { ... } },
      { loader: "font-awesome-loader" }
    ]
  }
]
```

## Don't Stringify Queries

This is the current pain point. To quote Tobias:

> For complex loader options you don't stringify the query. Instead you reference the ident of the options object. `my-loader??my-ident` will use the options object with the ident `my-ident`.

## Conclusion

Let me know if there's anything to clarify. I would love to see this work completed so we can refer to it in how to port to the new internals.

**Comment by justin808** [comment]
@bebraw can you submit a PR? Maybe we should bump the font-awesome-loader to v2? and only support webpack 2 for it?

**Comment by bebraw** [comment]
@justin808 v2 probably should be webpack 2 only although I suspect esp. the first point could be achieved for both 1 and 2 (likely a good intermediate step). I'll put it on my list.

**Comment by justin808** [comment]
@judahmeek, FYI.

**Comment by bebraw** [comment]
Hi,

I've been thinking about this. I think converting the loader to a plugin might serve the best. Here's my [WIP version](https://gist.github.com/bebraw/086b628bc44bb30e6305e4024fb62fe9). I still have to figure out how to pass the source to webpack without generating a temporary file (unavoidable?).

Usage would look like this:

```javascript
plugins: [
  new FontAwesomePlugin({
    styles: ['list', 'path'],
  }),
],
```

Maybe even `new FontAwesomePlugin(['list', 'path'])`, but object would be more forward looking.

Let me know if this would work for you.

**Comment by bebraw** [comment]
I think I got it. First we need a plugin like this:

```javascript
const path = require('path');
const qs = require('querystring');
const SingleEntryPlugin = require('webpack/lib/SingleEntryPlugin');

class FontAwesomePlugin {
  constructor(options) {
    this.options = options;
  }
  apply(compiler) {
    compiler.apply(new SingleEntryPlugin(
      this.context,
      path.join(__dirname, 'loader') + '?' + qs.stringify(this.options) + '!',
      this.options.entry || 'font-awesome'
    ));
  }
}

module.exports = FontAwesomePlugin;
```

That uses a loader internally:

```javascript
const loaderUtils = require('loader-utils');

module.exports = function () {
  const { styles } = loaderUtils.getOptions(this);
  const selectedStyles = [
    'mixins',
    'bordered-pulled',
    'core',
    'fixed-width',
    'icons',
    'larger',
    'list',
    'path',
    'rotated-flipped',
    'animated',
    'stacked',
  ].filter(style => styles.indexOf(style) >= 0);

  const selectedSource = selectedStyles.map(style => (
    `@import "~font-awesome/scss/_${style}.scss"`
  )).join('\n');

  return `
@import "~font-awesome/scss/_variables.scss";
$fa-font-path: "~font-awesome/fonts/";
@import "~font-awesome/scss/_icons.scss";

${selectedSource}
  `;
};
```

Usage looks like this:

```javascript
new AwesomePlugin({
  styles: ['core', 'icons'],
}),
```

In addition you have to configure SCSS and that's it.

**Comment by darrinholst** [comment]
Does font-awesome-loader + extract-text-webpack-plugin + webpack 2 not work? I got the impression from "work better" that it works. I'm getting the following and thought it might be something that I did wrong...

```
ERROR in ../~/font-awesome-loader/index.loader.js!./vendor/font-awesome.config.js
Module not found: Error: Can't resolve '[object Object],[object Object],[object Object],[object Object]' in '/Users/darrinholst/Projects/client/vendor'
 @ ../~/font-awesome-loader/index.loader.js!./vendor/font-awesome.config.js 1:0-270
 @ ./vendor/styles.js
 @ multi ./vendor/styles.js ./vendor/index.js
/
```

**Comment by bebraw** [comment]
@darrinholst It cannot work because of the way font-awesome-loader implements pitch loader. It's not compatible with webpack 2 ideas. I have suggested a plugin based approach above for the maintainers to consider.

**Comment by justin808** [comment]
Please see #8. Any PR, doc or code, that would make sense here?

**Comment by bebraw** [comment]
What I'm suggesting would be pretty much a whole rewrite (see the implementation above). If you want, feel free to pick up the code and rename to `font-awesome-plugin` as the loader portion is internal in my implementation (required to generate the code for the entry).

The usage would be a little different as then the user would have to configure SCSS, but other than that it seems straight-forward to me.

**Comment by bebraw** [comment]
I continued exploring the plugin path. It's probably doable, but it gets complex fast. I realized you can skip the loader bit by going directly through `node-sass` at the plugin. You then get some source that should be evaluated through webpack and written to a CSS file. That's the hard part to pull off.

Given there's a nice documentation PR (https://github.com/shakacode/font-awesome-loader/pull/8) in progress I'm going to close this.
